### ISSUE TITLE
error when running umis fastqtransform

### ISSUE THREAD

**Issue by lixin4306ren** [vals/umis#43]
Got the following error when running SureCell example data:

```
umis fastqtransform ~/tmp/src/umis/examples/SureCell/transform.json ~/tmp/src/umis/examples/SureCell/K562_R1.fastq ~/tmp/src/umis/examples/SureCell/K562_R2.fastq
INFO:umis.umis:Detected triple cellular indexes.
INFO:umis.umis:Detected UMI.
Traceback (most recent call last):
  File "/users/xinli/.local/bin/umis", line 11, in <module>
    load_entry_point('umis', 'console_scripts', 'umis')()
  File "/users/xinli/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/users/xinli/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/users/xinli/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/xinli/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/xinli/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/users/xinli/tmp/src/umis/umis/umis.py", line 285, in fastqtransform
    sys.stdout.write(read_template.format(**read1_dict))
KeyError: 'CB'
```

**Comment by roryk** [comment]
Hi Xin,

Sorry about that,  if you pass in the `--separate_cb` option it will work. Let us know if you need the triple cellular barcodes to be mashed together into one cellular barcode and we can add support for that. Keeping dual and triple indexed cellular barcodes separate with a delimiter is helpful when doing barcode filtering and correction downstream.

**Comment by lixin4306ren** [comment]
Thanks, it works. I didn't find full options in the document.

**Comment by roryk** [comment]
Great, glad it worked!
