### ISSUE TITLE
v1.0.8 yields KeyErrors when running test.sh

### ISSUE THREAD

**Issue by mfansler** [vals/umis#68]
Running the `test.sh` file on the v1.0.8 version leads to `KeyError` in test11 and test14. Pertinent log output:

```bash
INFO:umis.umis:Transforming examples/STRT-Seq/dualindex_example_1.fastq.
INFO:umis.umis:Detected dual cellular indexes.
INFO:umis.umis:Detected dual UMI.
Traceback (most recent call last):
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/bin/umis", line 33, in <module>
    sys.exit(load_entry_point('umis', 'console_scripts', 'umis')())
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mfansler/scratch/umis/umis/umis.py", line 299, in fastqtransform
    read1_dict['MB'] = read1_dict['MB1'] + read1_dict['MB2']
KeyError: 'MB1'

# ...

INFO:umis.umis:Transforming examples/Klein-inDrop/klein-v3_R1.fq.
INFO:umis.umis:Detected dual cellular indexes.
INFO:umis.umis:Detected dual UMI.
INFO:umis.umis:Detected sample.
Traceback (most recent call last):
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/bin/umis", line 33, in <module>
    sys.exit(load_entry_point('umis', 'console_scripts', 'umis')())
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mfansler/mambaforge-arm64/envs/test-umis/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mfansler/scratch/umis/umis/umis.py", line 299, in fastqtransform
    read1_dict['MB'] = read1_dict['MB1'] + read1_dict['MB2']
KeyError: 'MB1'

# ...

Files tests/results/test11.fq and tests/correct/test11.fq differ
Files tests/results/test14.fq and tests/correct/test14.fq differ
```

**Comment by tillea** [comment]
Any solution for this?

**Comment by tillea** [comment]
Ping?  Is this project alive?

Should we simply ignore / adapt the test?

Its reported also as [Debian bug](https://bugs.debian.org/1089115) and since test errors are release critical this issue prevents the package from being distributed inside official Debian.

**Comment by roryk** [comment]
Hey all! So sorry for the radio silence, I will fix this today.

**Comment by tillea** [comment]
I've seen Commit 0a425e7 but it does not seem to be related.  I any case it would be great if you could tag a new release once this issue as well as issue #72 are fixed.

Kind regards, Andreas.

**Comment by tillea** [comment]
Ping?

**Comment by tillea** [comment]
Ping, ping?
